# makefile for dev folder

rw : rw_mpz_t.cxx
	g++ rw_mpz_t.cxx -lgmp -o ../bin/rw_mpz_t
	
limit : limit.cxx
	g++ -std=c++17 limit.cxx -o ../bin/limit 

mod_chk : mod_chk.cxx
	g++ -std=c++17 mod_chk.cxx -o ../bin/modchk 
